# Form implementation generated from reading ui file '.\src\ui\UI_DialogAddStartup.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogAddStartup(object):
    def setupUi(self, DialogAddStartup):
        DialogAddStartup.setObjectName("DialogAddStartup")
        DialogAddStartup.resize(375, 250)
        DialogAddStartup.setMinimumSize(QtCore.QSize(375, 250))
        DialogAddStartup.setMaximumSize(QtCore.QSize(375, 250))
        self.btn_box = QtWidgets.QDialogButtonBox(parent=DialogAddStartup)
        self.btn_box.setGeometry(QtCore.QRect(198, 220, 171, 31))
        self.btn_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btn_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.btn_box.setObjectName("btn_box")
        self.layoutWidget = QtWidgets.QWidget(parent=DialogAddStartup)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add_file_path = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_add_file_path.setObjectName("btn_add_file_path")
        self.gridLayout.addWidget(self.btn_add_file_path, 1, 2, 1, 1)
        self.edit_passwd1 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.edit_passwd1.setObjectName("edit_passwd1")
        self.gridLayout.addWidget(self.edit_passwd1, 2, 1, 1, 1)
        self.edit_nickname = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.edit_nickname.setObjectName("edit_nickname")
        self.gridLayout.addWidget(self.edit_nickname, 0, 1, 1, 1)
        self.lab_passwd1_text = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lab_passwd1_text.setObjectName("lab_passwd1_text")
        self.gridLayout.addWidget(self.lab_passwd1_text, 2, 0, 1, 1)
        self.lab_nickname_text = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lab_nickname_text.setObjectName("lab_nickname_text")
        self.gridLayout.addWidget(self.lab_nickname_text, 0, 0, 1, 1)
        self.edit_passwd2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.edit_passwd2.setText("")
        self.edit_passwd2.setObjectName("edit_passwd2")
        self.gridLayout.addWidget(self.edit_passwd2, 3, 1, 1, 1)
        self.edit_file_path = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.edit_file_path.setReadOnly(True)
        self.edit_file_path.setObjectName("edit_file_path")
        self.gridLayout.addWidget(self.edit_file_path, 1, 1, 1, 1)
        self.lab_passwd2_text = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lab_passwd2_text.setObjectName("lab_passwd2_text")
        self.gridLayout.addWidget(self.lab_passwd2_text, 3, 0, 1, 1)
        self.lab_file_path_text = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lab_file_path_text.setObjectName("lab_file_path_text")
        self.gridLayout.addWidget(self.lab_file_path_text, 1, 0, 1, 1)

        self.retranslateUi(DialogAddStartup)
        self.btn_box.rejected.connect(DialogAddStartup.reject) # type: ignore
        self.edit_passwd1.textChanged['QString'].connect(self.edit_passwd2.setText) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogAddStartup)

    def retranslateUi(self, DialogAddStartup):
        _translate = QtCore.QCoreApplication.translate
        DialogAddStartup.setWindowTitle(_translate("DialogAddStartup", "Dialog"))
        self.btn_add_file_path.setText(_translate("DialogAddStartup", "导入"))
        self.edit_passwd1.setPlaceholderText(_translate("DialogAddStartup", "可导入文件自动识别(必填)"))
        self.edit_nickname.setPlaceholderText(_translate("DialogAddStartup", "用于区分战局锁(必填)"))
        self.lab_passwd1_text.setText(_translate("DialogAddStartup", "*密码1:"))
        self.lab_nickname_text.setText(_translate("DialogAddStartup", "*锁名称:"))
        self.edit_passwd2.setPlaceholderText(_translate("DialogAddStartup", "不填默认使用密码1"))
        self.edit_file_path.setPlaceholderText(_translate("DialogAddStartup", "支持文件拖拽导入"))
        self.lab_passwd2_text.setText(_translate("DialogAddStartup", "密码2:"))
        self.lab_file_path_text.setText(_translate("DialogAddStartup", "文件路径:"))
